
class Langs():
    
    def __init__(self):
        words = dict()
        functions = [self.cpp, 
            self.csharp, 
            self.java, 
            self.php,
            self.ruby, 
            self.c,
            self.javascript,
            self.javascript_other,
            self.python,
            self.go,
            self.operators,
            self.sql]

        for function in functions:
            for word in function():
                word = word.lower()
                if words.get(word, None) is None:
                    words[word] = 1
                else:
                    words[word] += 1

        self.words = words

    def is_programming_word(self, test_word):
        return self.words.get(test_word, None) is not None

    # http://en.cppreference.com/w/cpp/keyword
    @staticmethod
    def cpp(): 
        return {
            "alignas",
            "alignof",
            "and",
            "and_eq",
            "asm",
            "atomic_cancel",
            "atomic_commit",
            "atomic_noexcept",
            "auto",
            "bitand",
            "bitor",
            "bool",
            "break",
            "case",
            "catch",
            "char",
            "char16_t", 
            "char32_t", 
            "class", 
            "compl", 
            "concept", 
            "const", 
            "constexpr", 
            "const_cast", 
            "continue", 
            "decltype", 
            "default", 
            "delete", 
            "do", 
            "double", 
            "override", 
            "final", 
            "transaction_safe", 
            "transaction_safe_dynamic", 
            "if", 
            "elif", 
            "else", 
            "endif", 
            "defined", 
            "ifdef", 
            "ifndef", 
            "define", 
            "undef", 
            "include", 
            "line", 
            "error", 
            "pragma"
        }

    # http://msdn.microsoft.com/en-us/library/x53a06bb%28v=VS.100%29.aspx
    @staticmethod
    def csharp():
        return {
            "abstract",
            "as",
            "base",
            "bool",
            "break",
            "byte",
            "case",
            "catch",
            "char",
            "checked",
            "class",
            "const",
            "continue",
            "decimal",
            "default",
            "delegate",
            "do",
            "double",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "false",
            "finally",
            "fixed",
            "float",
            "for",
            "foreach",
            "goto",
            "if",
            "implicit",
            "in",
            "in (generic modifier)",
            "int",
            "interface",
            "internal",
            "is",
            "lock",
            "long",
            "namespace",
            "new",
            "null",
            "object",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "ref",
            "return",
            "sbyte",
            "sealed",
            "short",
            "sizeof",
            "stackalloc",
            "static",
            "string",
            "struct",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "uint",
            "ulong",
            "unchecked",
            "unsafe",
            "ushort",
            "using",
            "virtual",
            "void",
            "volatile",
            "while",
            "add",
            "alias",
            "ascending",
            "descending",
            "dynamic",
            "from",
            "get",
            "global",
            "group",
            "into",
            "join",
            "let",
            "orderby",
            "partial",
            "remove",
            "select",
            "set",
            "value",
            "var",
            "where",
            "yield"
        }

    # http://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html
    @staticmethod
    def java():
        return {
            "abstract",", "
            "continue",
            "for",
            "new",
            "switch",
            "assert",
            "default",
            "goto",
            "package",
            "synchronized",
            "boolean",
            "do",
            "if",
            "private",
            "this",
            "break",
            "double",
            "implements",
            "protected",
            "throw",
            "byte",
            "else",
            "import",
            "public",
            "throws",
            "case",
            "enum",
            "instanceof",
            "return",
            "transient",
            "catch",
            "extends",
            "int",
            "short",
            "try",
            "char",
            "final",
            "interface",
            "static",
            "void",
            "class",
            "finally",
            "long",
            "strictfp",
            "volatile",
            "const",
            "float",
            "native",
            "super",
            "while"
        }

    # http://php.net/manual/en/reserved.keywords.php
    @staticmethod
    def php():
        return {
            "__halt_compiler",", "
            "abstract",", "
            "and",
            "array",
            "as",
            "break",
            "callable", 
            "case",
            "catch",", "
            "class",
            "clone",
            "const",
            "continue",", "
            "declare",
            "default",
            "die",
            "do",
            "echo",
            "else",
            "elseif",
            "empty",
            "enddeclare",
            "endfor",
            "endforeach",
            "endif",
            "endswitch",
            "endwhile",
            "eval",
            "exit",
            "extends",
            "final",
            "finally",
            "for",
            "foreach",
            "function",
            "global",
            "goto",
            "if",
            "implements",
            "include",
            "include_once",
            "instanceof",
            "insteadof",
            "interface",
            "isset",
            "list",
            "namespace",
            "new",
            "or",
            "print",
            "private",
            "protected",
            "public",
            "require",
            "require_once",
            "return",
            "static",
            "switch",
            "throw",
            "trait",
            "try",
            "unset",
            "use",
            "var",
            "while",
            "xor",
            "yield",
            "__CLASS__",
            "__DIR__",
            "__FILE__",
            "__FUNCTION__",
            "__LINE__",
            "__METHOD__",
            "__NAMESPACE__",
            "__TRAIT__"
        }

    # http://ruby-doc.org/docs/keywords/1.9/
    @staticmethod
    def ruby():
        return {
            "BEGIN",
            "END",
            "__ENCODING__",
            "__END__",
            "__FILE__",
            "__LINE__",
            "alias",
            "and",
            "begin",
            "break",
            "case",
            "class",
            "def",
            "defined",
            "do",
            "else",
            "elsif",
            "end",
            "ensure",
            "false",
            "for",
            "if",
            "in",
            "module",
            "next",
            "nil",
            "not",
            "or",
            "redo",
            "rescue",
            "retry",
            "return",
            "self",
            "super",
            "then",
            "true",
            "undef",
            "unless",
            "until",
            "when",
            "while",
            "yield"
        }

    # http://tigcc.ticalc.org/doc/keywords.html
    @staticmethod
    def c():
        return {
            "auto",
            "break",
            "case",
            "char",
            "const",
            "continue",
            "default",
            "do",
            "double",
            "else",
            "enum",
            "extern",
            "float",
            "for",
            "goto",
            "if",
            "int",
            "long",
            "register",
            "return",
            "short",
            "signed",
            "sizeof",
            "static",
            "struct",
            "switch",
            "typedef",
            "union",
            "unsigned",
            "void",
            "volatile",
            "while"
        }
    # https://www.w3schools.com/js/js_reserved.asp
    @staticmethod
    def javascript():
        return {
            "abstract",
            "arguments",
            "await",
            "boolean",
            "break",
            "byte",
            "case",
            "catch",
            "char",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "double",
            "else",
            "enum",
            "eval",
            "export",
            "extends",
            "false",
            "final",
            "finally",
            "float",
            "for",
            "function",
            "goto",
            "if",
            "implements",
            "import",
            "in",
            "instanceof",
            "int",
            "interface",
            "let",
            "long",
            "native",
            "new",
            "null",
            "package",
            "private",
            "protected",
            "public",
            "return",
            "short",
            "static",
            "super",
            "switch",
            "synchronized",
            "this",
            "throw",
            "throws",
            "transient",
            "true",
            "try",
            "typeof",
            "var",
            "void",
            "volatile",
            "while",
            "with",
            "yield"
        }
    
    @staticmethod
    def javascript_other():
        return {
            "Array",
            "Date",
            "eval",
            "function",
            "hasOwnProperty",
            "Infinity",
            "isFinite",
            "isNaN",
            "isPrototypeOf",
            "length",
            "Math",
            "NaN",
            "name",
            "Number",
            "Object",
            "prototype",
            "String",
            "toString",
            "undefined",
            "valueOf",
            "alert",
            "all",
            "anchor",
            "anchors",
            "area",
            "assign",
            "blur",
            "button",
            "checkbox",
            "clearInterval",
            "clearTimeout",
            "clientInformation",
            "close",
            "closed",
            "confirm",
            "constructor",
            "crypto",
            "decodeURI",
            "decodeURIComponent",
            "defaultStatus",
            "document",
            "element",
            "elements",
            "embed",
            "embeds",
            "encodeURI",
            "encodeURIComponent",
            "escape",
            "event",
            "fileUpload",
            "focus",
            "form",
            "forms",
            "frame",
            "innerHeight",
            "innerWidth",
            "layer",
            "layers",
            "link",
            "location",
            "mimeTypes",
            "navigate",
            "navigator",
            "frames",
            "frameRate",
            "hidden",
            "history",
            "image",
            "images",
            "offscreenBuffering",
            "open",
            "opener",
            "option",
            "outerHeight",
            "outerWidth",
            "packages",
            "pageXOffset",
            "pageYOffset",
            "parent",
            "parseFloat",
            "parseInt",
            "password",
            "pkcs11",
            "plugin",
            "prompt",
            "propertyIsEnum",
            "radio",
            "reset",
            "screenX",
            "screenY",
            "scroll",
            "secure",
            "select",
            "self",
            "setInterval",
            "setTimeout",
            "status",
            "submit",
            "taint",
            "text",
            "textarea",
            "top",
            "unescape",
            "untaint",
            "window",
            "onblur",
            "onclick",
            "onerror",
            "onfocus",
            "onkeydown",
            "onkeypress",
            "onkeyup",
            "onmouseover",
            "onload",
            "onmouseup",
            "onmousedown",
            "onsubmit"
        }   
    
    # https://docs.python.org/3/reference/lexical_analysis.html#keywords
    @staticmethod
    def python():
        return {
            "False",
            "class",
            "finally",
            "is",
            "return",
            "None",
            "continue",
            "for",
            "lambda",
            "try",
            "True",
            "def",
            "from",
            "nonlocal",
            "while",
            "and",
            "del",
            "global",
            "not",
            "with",
            "as",
            "elif",
            "if",
            "or",
            "yield",
            "assert",
            "else",
            "import",
            "pass",
            "break",
            "except",
            "in",
            "raise"
        }
    # https://golang.org/ref/spec#Keywords
    @staticmethod
    def go():
        return {
            "break",
            "default",
            "func",
            "interface",
            "select",
            "case",
            "defer",
            "go",
            "map",
            "struct",
            "chan",
            "else",
            "goto",
            "package",
            "switch",
            "const",
            "fallthrough",
            "if",
            "range",
            "type",
            "continue",
            "for",
            "import",
            "return",
            "var"
        }
    
    @staticmethod
    def operators():
        return {
            "+",
            "&",
            "+=",
            "&=",
            "&&",
            "==",
            "!=",
            "(",
            ")",
            "-",
            "|",
            "-=",
            "|=",
            "||",
            "<",
            "<=",
            "[",
            "]",
            "*",
            "^",
            "*=",
            "^=",
            "<-",
            ">",
            ">=",
            "{",
            "}",
            "/",
            "<<",
            "/=",
            "<<=",
            "++",
            "=",
            ":=",
            ",",
            ";",
            "%",
            ">>",
            "%=",
            ">>=",
            "--",
            "!",
            "...",
            ".",
            ":",
            "&^",
            "&^="
        }
    # https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql    
    @staticmethod
    def sql():
        return {
            "ADD", "EXTERNAL", "PROCEDURE",
            "ALL", "FETCH", "PUBLIC",
            "ALTER", "FILE", "RAISERROR",
            "AND", "FILLFACTOR", "READ",
            "ANY", "FOR", "READTEXT",
            "AS", "FOREIGN", "RECONFIGURE",
            "ASC", "FREETEXT", "REFERENCES",
            "AUTHORIZATION", "FREETEXTTABLE", "REPLICATION",
            "BACKUP", "FROM", "RESTORE",
            "BEGIN", "FULL", "RESTRICT",
            "BETWEEN", "FUNCTION", "RETURN",
            "BREAK", "GOTO", "REVERT",
            "BULK", "GROUP", "RIGHT",
            "BY", "HAVING", "ROLLBACK",
            "CASCADE", "HOLDLOCK", "ROWCOUNT",
            "CASE", "IDENTITY", "ROWGUIDCOL",
            "CHECK", "IDENTITY_INSERT", "RULE",
            "CHECKPOINT", "IDENTITYCOL", "SAVE",
            "CLOSE", "IF", "SCHEMA",
            "CLUSTERED", "IN", "SECURITYAUDIT",
            "COALESCE", "INDEX", "SELECT",
            "COLLATE", "INNER", "SEMANTICKEYPHRASETABLE",
            "COLUMN", "INSERT", "SEMANTICSIMILARITYDETAILSTABLE",
            "COMMIT", "INTERSECT", "SEMANTICSIMILARITYTABLE",
            "COMPUTE", "INTO", "SESSION_USER",
            "CONSTRAINT", "IS", "SET",
            "CONTAINS", "JOIN", "SETUSER",
            "CONTAINSTABLE", "KEY", "SHUTDOWN",
            "CONTINUE", "KILL", "SOME",
            "CONVERT", "LEFT", "STATISTICS",
            "CREATE", "LIKE", "SYSTEM_USER",
            "CROSS", "LINENO", "TABLE",
            "CURRENT", "LOAD", "TABLESAMPLE",
            "CURRENT_DATE", "MERGE", "TEXTSIZE",
            "CURRENT_TIME", "NATIONAL", "THEN",
            "CURRENT_TIMESTAMP", "NOCHECK", "TO",
            "CURRENT_USER", "NONCLUSTERED", "TOP",
            "CURSOR", "NOT", "TRAN",
            "DATABASE", "NULL", "TRANSACTION",
            "DBCC", "NULLIF", "TRIGGER",
            "DEALLOCATE", "OF", "TRUNCATE",
            "DECLARE", "OFF", "TRY_CONVERT",
            "DEFAULT", "OFFSETS", "TSEQUAL",
            "DELETE", "ON", "UNION",
            "DENY", "OPEN", "UNIQUE",
            "DESC", "OPENDATASOURCE", "UNPIVOT",
            "DISK", "OPENQUERY", "UPDATE",
            "DISTINCT", "OPENROWSET", "UPDATETEXT",
            "DISTRIBUTED", "OPENXML", "USE",
            "DOUBLE", "OPTION", "USER",
            "DROP", "OR", "VALUES",
            "DUMP", "ORDER", "VARYING",
            "ELSE", "OUTER", "VIEW",
            "END", "OVER", "WAITFOR",
            "ERRLVL", "PERCENT", "WHEN",
            "ESCAPE", "PIVOT", "WHERE",
            "EXCEPT", "PLAN", "WHILE",
            "EXEC", "PRECISION", "WITH",
            "EXECUTE", "PRIMARY", "WITHIN GROUP",
            "EXISTS", "PRINT", "WRITETEXT",
            "EXIT", "PROC",
            "ABSOLUTE", "EXEC", "OVERLAPS",
            "ACTION", "EXECUTE", "PAD",
            "ADA", "EXISTS", "PARTIAL",
            "ADD", "EXTERNAL", "PASCAL",
            "ALL", "EXTRACT", "POSITION",
            "ALLOCATE", "FALSE", "PRECISION",
            "ALTER", "FETCH", "PREPARE",
            "AND", "FIRST", "PRESERVE",
            "ANY", "FLOAT", "PRIMARY",
            "ARE", "FOR", "PRIOR",
            "AS", "FOREIGN", "PRIVILEGES",
            "ASC", "FORTRAN", "PROCEDURE",
            "ASSERTION", "FOUND", "PUBLIC",
            "AT", "FROM", "READ",
            "AUTHORIZATION", "FULL", "REAL",
            "AVG", "GET", "REFERENCES",
            "BEGIN", "GLOBAL", "RELATIVE",
            "BETWEEN", "GO", "RESTRICT",
            "BIT", "GOTO", "REVOKE",
            "BIT_LENGTH", "GRANT", "RIGHT",
            "BOTH", "GROUP", "ROLLBACK",
            "BY", "HAVING", "ROWS",
            "CASCADE", "HOUR", "SCHEMA",
            "CASCADED", "IDENTITY", "SCROLL",
            "CASE", "IMMEDIATE", "SECOND",
            "CAST", "IN", "SECTION",
            "CATALOG", "INCLUDE", "SELECT",
            "CHAR", "INDEX", "SESSION",
            "CHAR_LENGTH", "INDICATOR", "SESSION_USER",
            "CHARACTER", "INITIALLY", "SET",
            "CHARACTER_LENGTH", "INNER", "SIZE",
            "CHECK", "INPUT", "SMALLINT",
            "CLOSE", "INSENSITIVE", "SOME",
            "COALESCE", "INSERT", "SPACE",
            "COLLATE", "INT", "SQL",
            "COLLATION", "INTEGER", "SQLCA",
            "COLUMN", "INTERSECT", "SQLCODE",
            "COMMIT", "INTERVAL", "SQLERROR",
            "CONNECT", "INTO", "SQLSTATE",
            "CONNECTION", "IS", "SQLWARNING",
            "CONSTRAINT", "ISOLATION", "SUBSTRING",
            "CONSTRAINTS", "JOIN", "SUM",
            "CONTINUE", "KEY", "SYSTEM_USER",
            "CONVERT", "LANGUAGE", "TABLE",
            "CORRESPONDING", "LAST", "TEMPORARY",
            "COUNT", "LEADING", "THEN",
            "CREATE", "LEFT", "TIME",
            "CROSS", "LEVEL", "TIMESTAMP",
            "CURRENT", "LIKE", "TIMEZONE_HOUR",
            "CURRENT_DATE", "LOCAL", "TIMEZONE_MINUTE",
            "CURRENT_TIME", "LOWER", "TO",
            "CURRENT_TIMESTAMP", "MATCH", "TRAILING",
            "CURRENT_USER", "MAX", "TRANSACTION",
            "CURSOR", "MIN", "TRANSLATE",
            "DATE", "MINUTE", "TRANSLATION",
            "DAY", "MODULE", "TRIM",
            "DEALLOCATE", "MONTH", "TRUE",
            "DEC", "NAMES", "UNION",
            "DECIMAL", "NATIONAL", "UNIQUE",
            "DECLARE", "NATURAL", "UNKNOWN",
            "DEFAULT", "NCHAR", "UPDATE",
            "DEFERRABLE", "NEXT", "UPPER",
            "DEFERRED", "NO", "USAGE",
            "DELETE", "NONE", "USER",
            "DESC", "NOT", "USING",
            "DESCRIBE", "NULL", "VALUE",
            "DESCRIPTOR", "NULLIF", "VALUES",
            "DIAGNOSTICS", "NUMERIC", "VARCHAR",
            "DISCONNECT", "OCTET_LENGTH", "VARYING",
            "DISTINCT", "OF", "VIEW",
            "DOMAIN", "ON", "WHEN",
            "DOUBLE", "ONLY", "WHENEVER",
            "DROP", "OPEN", "WHERE",
            "ELSE", "OPTION", "WITH",
            "END", "OR", "WORK",
            "END-EXEC", "ORDER", "WRITE",
            "ESCAPE", "OUTER", "YEAR",
            "EXCEPT", "OUTPUT", "ZONE",
            "EXCEPTION"
        }